import './globals.css'
import type { Metadata } from 'next'
//context
import CartProvider from '@/context/cartContext'
//fonts
import { Bangers, Quicksand, Roboto_Condensed } from 'next/font/google'
import { Banner, CartDesktop, CartIcon, CartMobile, Footer } from '@/components'
const bangers = Bangers({
  subsets: ['latin'],
  variable: '--font-bangers',
  weight: '400',
  style: 'normal',
})

const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'],
  variable: '--font-robotoCondensed',
  weight: '400',
  style: 'normal',
})

const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand',
})
export const metadata: Metadata = {
  title: 'PIZZALAND',
  description: 'Generated by create next app',
  icons: {
    icon: ['/metaIcon/favicon.ico?v=4'],
    apple: ['/metaIcon/apple-touch-icon.png?v=4'],
    shortcut: ['/metaIcon/apple-touch-icon.png'],
  },
  manifest: '/metaIcon/site.webmanifest',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <CartProvider>
      <html lang="en">
        <body
          className={`${bangers.variable} ${robotoCondensed.variable} ${quicksand.variable} font-quicksand`}
        >
          <Banner />
          {children}
          <CartDesktop />
          <CartMobile />
          <CartIcon />
          <Footer />
        </body>
      </html>
    </CartProvider>
  )
}
